# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AI WORKERS' INQUIRY
subtitle: A FAccT 2025 CRAFT Session that brings together workers, organizers, and labor experts to explore how AI is transforming our workplaces and discuss strategies for collective resistance
date: June 23, 2025
timeframe: 4:15 PM-6:30 PM UTC+3
location: Athens, Greece and Online
favicon: "images/favicon.png"
description: "AI Workers' Inquiry is a FAccT 2025 CRAFT workshop that brings together workers, organizers, and labor experts to explore how AI is transforming our workplaces and discuss strategies for collective resistance"
bannerimg: "https://ai-workers-inquiry.github.io/images/banner.png"
headerimg: "https://ai-workers-inquiry.github.io/images/header.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "ai-workers-inquiry.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
